  overseerr:
    fullnameOverride: overseerr
    configPath: /app/config
    image:
      organization: sctx
      repository: overseerr
      tag: develop
    service:
      port: 5055
    env:
      TZ: America/Chicago
      LOG_LEVEL: debug
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: request-beta.cajun.pro
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: [request-beta.cajun.pro]
          secretName: request-beta-cajun-pro
    persistence:
      type: statefulset
      config:
        accessMode: ReadWriteMany
        size: 10Gi
        storageClass: rook-cephfs
    resources:
      requests:
        cpu: 100m
        memory: 128m
    nodeSelector:
      cajun.pro/cluster-gen: "2"
