apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
    cert-manager.io/cluster-issuer: le-production
  labels:
    app: cajun-pro
  name: cajun-pro
spec:
  rules:
    - host: cajun.pro
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /
  tls:
    - hosts:
        - cajun.pro
      secretName: cert-cajun-pro
