traefik:
  fullnameOverride: traefik
  image:
    tag: 2.3.1
  globalArguments:
    - "--global.checknewversion"
    - "--serverstransport.insecureskipverify=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    - "--entryPoints.websecure.http.tls=true"
    - "--metrics.prometheus.entryPoint=metrics"
  logs:
    general:
      format: json
    access:
      enabled: true
      format: json
  metrics:
    prometheus:
      enabled: true
      entryPoint: metrics
  service:
    spec:
      externalTrafficPolicy: Local
  ports:
    web:
      redirectTo: websecure
    metrics:
      port: 8082
      expose: true
      exposedPort: 8082
  ingressRoute:
    dashboard:
      enabled: false
  ingressClass:
    enabled: true
    isDefaultClass: "true"
  pilot:
    enabled: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - traefik
            topologyKey: kubernetes.io/hostname

tfa:
  fullnameOverride: traefik-forward-auth
  cookie:
    domain: "cajun.pro,nickflix.io"
  logging:
    level: debug
    format: json
  providers:
    google:
      enabled: true
  middleware:
    enabled: true
    name: "google-auth"
  secret: "-"
  env:
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: traefik-forward-auth
          key: secret
    - name: PROVIDERS_GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: traefik-forward-auth
          key: google-client-id
    - name: PROVIDERS_GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: traefik-forward-auth
          key: google-client-secret
    - name: WHITELIST
      valueFrom:
        secretKeyRef:
          name: traefik-forward-auth
          key: whitelist
#   - name: INSECURE_COOKIE 12:30-2 2:30 onward PST
#     value: "true"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "50"
