apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-do
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: ingress
    name: do
  project: default
  source:
    path: traefik
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-do.yaml
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
