apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-home
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    name: home
  project: default
  source:
    path: traefik
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-home.yaml
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
  syncPolicy:
    automated: {}
