secrets-store-csi-driver:
  fullnameOverride: csi-secrets-store

  linux:
    image:
      repository: k8s.gcr.io/csi-secrets-store/driver
      tag: v1.2.4

    registrarImage:
      repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
      tag: v2.5.1

    livenessProbeImage:
      repository: k8s.gcr.io/sig-storage/livenessprobe
      tag: v2.9.0

  logVerbosity: 0
  logFormatJSON: false

  rbac:
    install: true

  syncSecret:
    enabled: true

  enableSecretRotation: true
  rotationPollInterval: "120s"
  # label: secrets-store.csi.k8s.io/used: "true"
  filteredWatchSecret: false
