---
apiVersion: v1
kind: Service
metadata:
  name: rtorrent
  labels:
    app: rtorrent
spec:
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: web
  - port: 50105
    targetPort: 50105
    protocol: TCP
    name: seed
  selector:
    app: rtorrent
